Inventory/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("delivery/", views.delivery, name="delivery"),
    path("delivery/add", views.adddelivery, name="adddelivery"),
]

Pearventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("Inventory.urls")),
    path("admin/", admin.site.urls),
]

Inventory/models.py
from django.db import models
from datetime import date
from django.core.validators import MinValueValidator


class Delivery(models.Model):
    TYPE_CHOICES = {
        "IN": "Indelivery",
        "OUT": "Outdelivery",
    }
    site = models.ForeignKey("Storage", on_delete=models.CASCADE)
    amount = models.IntegerField(default=0, validators=[MinValueValidator(1)])
    deliveryType = models.CharField(max_length=3, choices=TYPE_CHOICES)
    date = models.DateField(default=date.today)

    def __str__(self):
        return str(self.site) + ", " + str(self.deliveryType) + ", " + str(self.amount)


class Storage(models.Model):
    site = models.ForeignKey("Site", on_delete=models.CASCADE)
    product = models.ForeignKey("Product", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.site) + ", " + str(self.product)


class Site(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    price = models.IntegerField(default=0)

    def __str__(self):
        return self.name

Inventory/forms.py
from django import forms
from django.core.validators import MinValueValidator

from .models import Delivery


class DeliveryForm(forms.ModelForm):
    class Meta:
        model = Delivery
        fields = ["site", "amount", "deliveryType", "date"]
        widgets = {
            "date": forms.DateInput(
                attrs={"class": "form-control", "id": "datepicker"}
            ),
        }
        validators = {
            "amount": [
                MinValueValidator(1, message="Amount must be greater than zero.")
            ],
        }

Inventory/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.template import loader
from django.db.models import F, Sum, Case, When, IntegerField
from .forms import DeliveryForm
from django.contrib import messages

# Create your views here.
from .models import Delivery, Site, Storage, Product


def index(request):
    output = Delivery.objects.values(
        "site__site__name", "site__product__name"
    ).annotate(
        stock=Sum(
            Case(
                When(deliveryType="IN", then=F("amount")),
                default=0,
                output_field=IntegerField(),
            )
        )
        - Sum(
            Case(
                When(deliveryType="OUT", then=F("amount")),
                default=0,
                output_field=IntegerField(),
            )
        )
    )

    stock_by_site = {}

    # Organizing output into a dictionary
    for entry in output:
        site_name = entry["site__site__name"]
        product_name = entry["site__product__name"]
        stock = entry["stock"]

        if site_name not in stock_by_site:
            stock_by_site[site_name] = {}

        stock_by_site[site_name][product_name] = stock

    template = loader.get_template("inventory/index.html")
    context = {"stocks": stock_by_site}
    return HttpResponse(template.render(context, request))


def delivery(request):
    storages = Storage.objects.all()
    grouped_deliveries = {}

    for storage in storages:
        deliveries_to_storage = Delivery.objects.filter(site=storage).order_by("-date")
        if storage.site.name not in grouped_deliveries:
            grouped_deliveries[storage.site.name] = {}

        deliveries = list(deliveries_to_storage)
        balance = 0
        for delivery in deliveries:
            if delivery.deliveryType == "IN":
                balance += delivery.amount
            elif delivery.deliveryType == "OUT":
                balance -= delivery.amount

        grouped_deliveries[storage.site.name][storage.product.name] = {
            "deliveries": deliveries,
            "balance": balance,
        }
    template = loader.get_template("inventory/delivery.html")
    context = {"grouped_deliveries": grouped_deliveries}
    return HttpResponse(template.render(context, request))


def adddelivery(request):
    if request.method == "POST":
        form = DeliveryForm(request.POST)

        if form.is_valid():
            delivery = form.save(commit=False)
            delivery.save()
            messages.success(request, "Delivery added successfully.")
            return redirect("adddelivery")
    else:
        form = DeliveryForm()
    template = loader.get_template("inventory/add_delivery.html")
    context = {"form": form}
    return HttpResponse(template.render(context, request))

Inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>
      {% block title %}
        Pearventory
      {% endblock title %}
    </title>
    <meta charset="UTF-8" />
    <meta name="description"
          content="This webpage is to be used as an inventory management system where users can add deliveries at or to locations for products">
    <meta name="keywords" content="Inventory management system, OMS">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
          rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css"
          rel="stylesheet" />
  </head>
  <body style="padding-bottom: 80px;">
    <div class="container-fluid px-2 pr-2 mb-10">
      <div class="custom-max-width">
        {% block content %}
        {% endblock content %}
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <footer>
      <nav class="navbar fixed-bottom navbar-light bg-light">
        <div class="container-fluid justify-content-around custom-max-width">
          <a class="navbar-brand d-flex justify-content-center align-items-center btn btn-primary"
             style="width: 30%"
             href="{% url 'index' %}">Stock</a>
          <a class="navbar-brand d-flex justify-content-center align-items-center btn btn-primary"
             style="width: 30%"
             href="{% url 'delivery' %}">Deliveries</a>
          <a class="navbar-brand d-flex justify-content-center align-items-center btn btn-primary"
             style="width: 30%"
             href="{% url 'adddelivery' %}">New Delivery</a>
        </div>
      </nav>
    </footer>
  </body>
  <style>
    .custom-max-width {
      max-width: 1000px; /* Adjust this value to your preferred max-width */
      margin-left: auto;
      margin-right: auto;
    }
  </style>
</html>

Inventory/templates/inventory/add_delivery.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}
  Add Delivery
{% endblock title %}
{% block content %}
  <h1 class="mt-4 mb-4 text-center">Add Delivery</h1>
  <form method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id_site" class="form-label">Storage:</label>
      {% render_field form.site class="form-control searchable" %}
    </div>
    <div class="mb-3">
      <label for="id_amount" class="form-label">Amount:</label>
      {% render_field form.amount class="form-control" %}
    </div>
    <div class="mb-3">
      <label for="id_deliveryType" class="form-label">Delivery Type:</label>
      {% render_field form.deliveryType class="form-select" %}
    </div>
    <div class="mb-3">
      <label for="id_date" class="form-label">Date:</label>
      <input type="text" class="form-control" id="datepicker" name="date" />
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  {% if form.errors %}
    <div class="alert alert-danger mt-2">
      <strong>Error:</strong>
      {% for field in form %}
        {% for error in field.errors %}<p>{{ error }}{{ field.label }}</p>{% endfor %}
      {% endfor %}
    </div>
  {% endif %}
  {% if messages %}
    {% for message in messages %}<div class="alert alert-success mt-2" role="alert">{{ message }}</div>{% endfor %}
  {% endif %}
  <script>
  $(document).ready(function () {
    $("#datepicker").datepicker({
      format: "yyyy-mm-dd",
      autoclose: true,
      todayHighlight: true,
    });
    
  });
  $(".searchable").select2({
     width: '100%',
     theme: 'bootstrap-5'
        
        
      });
    
  </script>
{% endblock content %}

Inventory/templates/inventory/delivery.html
{% extends "base.html" %}
{% block title %}
  Deliveries
{% endblock title %}
{% block content %}
  <h1 class="mt-4 mb-4 text-center">Delivery Information</h1>
  {% for place, products in grouped_deliveries.items %}
    <div class="card mb-4">
      <div class="card-header">
        <h2 class="card-title text-center">{{ place }}</h2>
      </div>
      <div class="card-body">
        <div class="row">
          {% for product, data in products.items %}
            {% if forloop.counter0|divisibleby:3 %}
            </div>
            <div class="row mt-4">
            {% endif %}
            <div class="col-md-4">
              <div class="card mb-4">
                <div class="card-header">
                  <h2 class="card-title text-center">
                    {{ product }} -
                    <br>
                    {{ data.balance }}
                  </h2>
                </div>
                <div class="card-body" style="max-height: 250px; overflow-y: auto">
                  <ul class="list-group" style="list-style: none; padding-left: 0">
                    {% for delivery in data.deliveries %}
                      <li class="mb-2 p-2 d-flex align-items-center">
                        <span class="col-auto circle {% if delivery.deliveryType == 'OUT' %}bg-danger{% elif delivery.deliveryType == 'IN' %}bg-success{% endif %}"></span>
                        <span class="col d-flex align-items-center">
                          <span class="w-100 text-center">{{ delivery.date|date:"Y-m-d" }}</span>
                        </span>
                        <span class="col-auto badge bg-primary rounded-pill" style="width: 85px;">{{ delivery.amount }}</span>
                      </li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  {% endfor %}
  <style>
.circle {
width: 15px;
height: 15px;
border-radius: 50%;
display: inline-block;
}
  </style>
{% endblock content %}

Inventory/templates/inventory/index.html
{% extends "base.html" %}
{% block title %}
  Index
{% endblock title %}
{% block content %}
  <div class="container">
    <h1 class="mt-4 mb-4 text-center">Stock Information</h1>
    <div class="row">
      {% for site, products in stocks.items %}
        <div class="col-md-6">
          <div class="card mb-4">
            <div class="card-header">
              <h2 class="card-title text-center">{{ site }}</h2>
            </div>
            <div class="card-body">
              <ul class="list-group">
                {% for product, stock in products.items %}
                  <li class="list-group-item d-flex justify-content-between ">
                    <div class="text-start">
                      <span class="fw-bold">{{ product }}</span>
                    </div>
                    <div class="text-end" style="width: 85px;">
                      <span class="badge bg-primary rounded-pill" style="width: 100%;">{{ stock }}</span>
                    </div>
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}